const typeDictory = {"application/vnd.hzn-3d-crossword": {"desc": "3D Crossword Plugin", "ext": ".x3d"},
    "video/3gpp": {"desc": "3GP", "ext": ".3gp"},
    "video/3gpp2": {"desc": "3GP2", "ext": ".3g2"},
    "application/vnd.mseq": {"desc": "3GPP MSEQ File", "ext": ".mseq"},
    "application/vnd.3m.post-it-notes": {"desc": "3M Post It Notes", "ext": ".pwn"},
    "application/vnd.3gpp.pic-bw-large": {"desc": "3rd Generation Partnership Project - Pic Large", "ext": ".plb"},
    "application/vnd.3gpp.pic-bw-small": {"desc": "3rd Generation Partnership Project - Pic Small", "ext": ".psb"},
    "application/vnd.3gpp.pic-bw-var": {"desc": "3rd Generation Partnership Project - Pic Var", "ext": ".pvb"},
    "application/vnd.3gpp2.tcap": {"desc": "3rd Generation Partnership Project - Transaction Capabilities Application Part", "ext": ".tcap"},
    "application/x-7z-compressed": {"desc": "7-Zip", "ext": ".7z"},
    "application/x-abiword": {"desc": "AbiWord", "ext": ".abw"},
    "application/x-ace-compressed": {"desc": "Ace Archive", "ext": ".ace"},
    "application/vnd.americandynamics.acc": {"desc": "Active Content Compression", "ext": ".acc"},
    "application/vnd.acucobol": {"desc": "ACU Cobol", "ext": ".acu"},
    "application/vnd.acucorp": {"desc": "ACU Cobol", "ext": ".atc"},
    "audio/adpcm": {"desc": "Adaptive differential pulse-code modulation", "ext": ".adp"},
    "application/x-authorware-bin": {"desc": "Adobe (Macropedia) Authorware - Binary File", "ext": ".aab"},
    "application/x-authorware-map": {"desc": "Adobe (Macropedia) Authorware - Map", "ext": ".aam"},
    "application/x-authorware-seg": {"desc": "Adobe (Macropedia) Authorware - Segment File", "ext": ".aas"},
    "application/vnd.adobe.air-application-installer-package+zip": {"desc": "Adobe AIR Application", "ext": ".air"},
    "application/x-shockwave-flash": {"desc": "Adobe Flash", "ext": ".swf"},
    "application/vnd.adobe.fxp": {"desc": "Adobe Flex Project", "ext": ".fxp"},
    "application/pdf": {"desc": "Adobe Portable Document Format", "ext": ".pdf"},
    "application/vnd.cups-ppd": {"desc": "Adobe PostScript Printer Description File Format", "ext": ".ppd"},
    "application/x-director": {"desc": "Adobe Shockwave Player", "ext": ".dir"},
    "application/vnd.adobe.xdp+xml": {"desc": "Adobe XML Data Package", "ext": ".xdp"},
    "application/vnd.adobe.xfdf": {"desc": "Adobe XML Forms Data Format", "ext": ".xfdf"},
    "audio/x-aac": {"desc": "Advanced Audio Coding (AAC)", "ext": ".aac"},
    "application/vnd.ahead.space": {"desc": "Ahead AIR Application", "ext": ".ahead"},
    "application/vnd.airzip.filesecure.azf": {"desc": "AirZip FileSECURE", "ext": ".azf"},
    "application/vnd.airzip.filesecure.azs": {"desc": "AirZip FileSECURE", "ext": ".azs"},
    "application/vnd.amazon.ebook": {"desc": "Amazon Kindle eBook format", "ext": ".azw"},
    "application/vnd.amiga.ami": {"desc": "AmigaDE", "ext": ".ami"},
    "application/andrew-inset": {"desc": "Andrew Toolkit", "ext": "N/A"},
    "application/vnd.android.package-archive": {"desc": "Android Package Archive", "ext": ".apk"},
    "application/vnd.anser-web-certificate-issue-initiation": {"desc": "ANSER-WEB Terminal Client - Certificate Issue", "ext": ".cii"},
    "application/vnd.anser-web-funds-transfer-initiation": {"desc": "ANSER-WEB Terminal Client - Web Funds Transfer", "ext": ".fti"},
    "application/vnd.antix.game-component": {"desc": "Antix Game Player", "ext": ".atx"},
    "application/vnd.apple.installer+xml": {"desc": "Apple Installer Package", "ext": ".mpkg"},
    "application/applixware": {"desc": "Applixware", "ext": ".aw"},
    "application/vnd.hhe.lesson-player": {"desc": "Archipelago Lesson Player", "ext": ".les"},
    "application/vnd.aristanetworks.swi": {"desc": "Arista Networks Software Image", "ext": ".swi"},
    "text/x-asm": {"desc": "Assembler Source File", "ext": ".s"},
    "application/atomcat+xml": {"desc": "Atom Publishing Protocol", "ext": ".atomcat"},
    "application/atomsvc+xml": {"desc": "Atom Publishing Protocol Service Document", "ext": ".atomsvc"},
    "application/atom+xml": {"desc": "Atom Syndication Format", "ext": ["atom, .xml"]},
    "application/pkix-attr-cert": {"desc": "Attribute Certificate", "ext": ".ac"},
    "audio/x-aiff": {"desc": "Audio Interchange File Format", "ext": ".aif"},
    "video/x-msvideo": {"desc": "Audio Video Interleave (AVI)", "ext": ".avi"},
    "application/vnd.audiograph": {"desc": "Audiograph", "ext": ".aep"},
    "image/vnd.dxf": {"desc": "AutoCAD DXF", "ext": ".dxf"},
    "model/vnd.dwf": {"desc": "Autodesk Design Web Format (DWF)", "ext": ".dwf"},
    "text/plain-bas": {"desc": "BAS Partitur Format", "ext": ".par"},
    "application/x-bcpio": {"desc": "Binary CPIO Archive", "ext": ".bcpio"},
    "application/octet-stream": {"desc": "Binary Data", "ext": ".bin"},
    "image/bmp": {"desc": "Bitmap Image File", "ext": ".bmp"},
    "application/x-bittorrent": {"desc": "BitTorrent", "ext": ".torrent"},
    "application/vnd.rim.cod": {"desc": "Blackberry COD File", "ext": ".cod"},
    "application/vnd.blueice.multipass": {"desc": "Blueice Research Multipass", "ext": ".mpm"},
    "application/vnd.bmi": {"desc": "BMI Drawing Data Interchange", "ext": ".bmi"},
    "application/x-sh": {"desc": "Bourne Shell Script", "ext": ".sh"},
    "image/prs.btif": {"desc": "BTIF", "ext": ".btif"},
    "application/vnd.businessobjects": {"desc": "BusinessObjects", "ext": ".rep"},
    "application/x-bzip": {"desc": "Bzip Archive", "ext": ".bz"},
    "application/x-bzip2": {"desc": "Bzip2 Archive", "ext": ".bz2"},
    "application/x-csh": {"desc": "C Shell Script", "ext": ".csh"},
    "text/x-c": {"desc": "C Source File", "ext": ".c"},
    "application/vnd.chemdraw+xml": {"desc": "CambridgeSoft Chem Draw", "ext": ".cdxml"},
    "text/css": {"desc": "Cascading Style Sheets (CSS)", "ext": ".css"},
    "chemical/x-cdx": {"desc": "ChemDraw eXchange file", "ext": ".cdx"},
    "chemical/x-cml": {"desc": "Chemical Markup Language", "ext": ".cml"},
    "chemical/x-csml": {"desc": "Chemical Style Markup Language", "ext": ".csml"},
    "application/vnd.contact.cmsg": {"desc": "CIM Database", "ext": ".cdbcmsg"},
    "application/vnd.claymore": {"desc": "Claymore Data Files", "ext": ".cla"},
    "application/vnd.clonk.c4group": {"desc": "Clonk Game", "ext": ".c4g"},
    "image/vnd.dvb.subtitle": {"desc": "Close Captioning - Subtitle", "ext": ".sub"},
    "application/cdmi-capability": {"desc": "Cloud Data Management Interface (CDMI) - Capability", "ext": ".cdmia"},
    "application/cdmi-container": {"desc": "Cloud Data Management Interface (CDMI) - Contaimer", "ext": ".cdmic"},
    "application/cdmi-domain": {"desc": "Cloud Data Management Interface (CDMI) - Domain", "ext": ".cdmid"},
    "application/cdmi-object": {"desc": "Cloud Data Management Interface (CDMI) - Object", "ext": ".cdmio"},
    "application/cdmi-queue": {"desc": "Cloud Data Management Interface (CDMI) - Queue", "ext": ".cdmiq"},
    "application/vnd.cluetrust.cartomobile-config": {"desc": "ClueTrust CartoMobile - Config", "ext": ".c11amc"},
    "application/vnd.cluetrust.cartomobile-config-pkg": {"desc": "ClueTrust CartoMobile - Config Package", "ext": ".c11amz"},
    "image/x-cmu-raster": {"desc": "CMU Image", "ext": ".ras"},
    "model/vnd.collada+xml": {"desc": "COLLADA", "ext": ".dae"},
    "text/csv": {"desc": "Comma-Separated Values", "ext": ".csv"},
    "application/mac-compactpro": {"desc": "Compact Pro", "ext": ".cpt"},
    "application/vnd.wap.wmlc": {"desc": "Compiled Wireless Markup Language (WMLC)", "ext": ".wmlc"},
    "image/cgm": {"desc": "Computer Graphics Metafile", "ext": ".cgm"},
    "x-conference/x-cooltalk": {"desc": "CoolTalk", "ext": ".ice"},
    "image/x-cmx": {"desc": "Corel Metafile Exchange (CMX)", "ext": ".cmx"},
    "application/vnd.xara": {"desc": "CorelXARA", "ext": ".xar"},
    "application/vnd.cosmocaller": {"desc": "CosmoCaller", "ext": ".cmc"},
    "application/x-cpio": {"desc": "CPIO Archive", "ext": ".cpio"},
    "application/vnd.crick.clicker": {"desc": "CrickSoftware - Clicker", "ext": ".clkx"},
    "application/vnd.crick.clicker.keyboard": {"desc": "CrickSoftware - Clicker - Keyboard", "ext": ".clkk"},
    "application/vnd.crick.clicker.palette": {"desc": "CrickSoftware - Clicker - Palette", "ext": ".clkp"},
    "application/vnd.crick.clicker.template": {"desc": "CrickSoftware - Clicker - Template", "ext": ".clkt"},
    "application/vnd.crick.clicker.wordbank": {"desc": "CrickSoftware - Clicker - Wordbank", "ext": ".clkw"},
    "application/vnd.criticaltools.wbs+xml": {"desc": "Critical Tools - PERT Chart EXPERT", "ext": ".wbs"},
    "application/vnd.rig.cryptonote": {"desc": "CryptoNote", "ext": ".cryptonote"},
    "chemical/x-cif": {"desc": "Crystallographic Interchange Format", "ext": ".cif"},
    "chemical/x-cmdf": {"desc": "CrystalMaker Data Format", "ext": ".cmdf"},
    "application/cu-seeme": {"desc": "CU-SeeMe", "ext": ".cu"},
    "application/prs.cww": {"desc": "CU-Writer", "ext": ".cww"},
    "text/vnd.curl": {"desc": "Curl - Applet", "ext": ".curl"},
    "text/vnd.curl.dcurl": {"desc": "Curl - Detached Applet", "ext": ".dcurl"},
    "text/vnd.curl.mcurl": {"desc": "Curl - Manifest File", "ext": ".mcurl"},
    "text/vnd.curl.scurl": {"desc": "Curl - Source Code", "ext": ".scurl"},
    "application/vnd.curl.car": {"desc": "CURL Applet", "ext": ".car"},
    "application/vnd.curl.pcurl": {"desc": "CURL Applet", "ext": ".pcurl"},
    "application/vnd.yellowriver-custom-menu": {"desc": "CustomMenu", "ext": ".cmp"},
    "application/dssc+der": {"desc": "Data Structure for the Security Suitability of Cryptographic Algorithms", "ext": ".dssc"},
    "application/dssc+xml": {"desc": "Data Structure for the Security Suitability of Cryptographic Algorithms", "ext": ".xdssc"},
    "application/x-debian-package": {"desc": "Debian Package", "ext": ".deb"},
    "audio/vnd.dece.audio": {"desc": "DECE Audio", "ext": ".uva"},
    "image/vnd.dece.graphic": {"desc": "DECE Graphic", "ext": ".uvi"},
    "video/vnd.dece.hd": {"desc": "DECE High Definition Video", "ext": ".uvh"},
    "video/vnd.dece.mobile": {"desc": "DECE Mobile Video", "ext": ".uvm"},
    "video/vnd.uvvu.mp4": {"desc": "DECE MP4", "ext": ".uvu"},
    "video/vnd.dece.pd": {"desc": "DECE PD Video", "ext": ".uvp"},
    "video/vnd.dece.sd": {"desc": "DECE SD Video", "ext": ".uvs"},
    "video/vnd.dece.video": {"desc": "DECE Video", "ext": ".uvv"},
    "application/x-dvi": {"desc": "Device Independent File Format (DVI)", "ext": ".dvi"},
    "application/vnd.fdsn.seed": {"desc": "Digital Siesmograph Networks - SEED Datafiles", "ext": ".seed"},
    "application/x-dtbook+xml": {"desc": "Digital Talking Book", "ext": ".dtb"},
    "application/x-dtbresource+xml": {"desc": "Digital Talking Book - Resource File", "ext": ".res"},
    "application/vnd.dvb.ait": {"desc": "Digital Video Broadcasting", "ext": ".ait"},
    "application/vnd.dvb.service": {"desc": "Digital Video Broadcasting", "ext": ".svc"},
    "audio/vnd.digital-winds": {"desc": "Digital Winds Music", "ext": ".eol"},
    "image/vnd.djvu": {"desc": "DjVu", "ext": ".djvu"},
    "application/xml-dtd": {"desc": "Document Type Definition", "ext": ".dtd"},
    "application/vnd.dolby.mlp": {"desc": "Dolby Meridian Lossless Packing", "ext": ".mlp"},
    "application/x-doom": {"desc": "Doom Video Game", "ext": ".wad"},
    "application/vnd.dpgraph": {"desc": "DPGraph", "ext": ".dpg"},
    "audio/vnd.dra": {"desc": "DRA Audio", "ext": ".dra"},
    "application/vnd.dreamfactory": {"desc": "DreamFactory", "ext": ".dfac"},
    "audio/vnd.dts": {"desc": "DTS Audio", "ext": ".dts"},
    "audio/vnd.dts.hd": {"desc": "DTS High Definition Audio", "ext": ".dtshd"},
    "image/vnd.dwg": {"desc": "DWG Drawing", "ext": ".dwg"},
    "application/vnd.dynageo": {"desc": "DynaGeo", "ext": ".geo"},
    "application/ecmascript": {"desc": "ECMAScript", "ext": ".es"},
    "application/vnd.ecowin.chart": {"desc": "EcoWin Chart", "ext": ".mag"},
    "image/vnd.fujixerox.edmics-mmr": {"desc": "EDMICS 2000", "ext": ".mmr"},
    "image/vnd.fujixerox.edmics-rlc": {"desc": "EDMICS 2000", "ext": ".rlc"},
    "application/exi": {"desc": "Efficient XML Interchange", "ext": ".exi"},
    "application/vnd.proteus.magazine": {"desc": "EFI Proteus", "ext": ".mgz"},
    "application/epub+zip": {"desc": "Electronic Publication", "ext": ".epub"},
    "message/rfc822": {"desc": "Email Message", "ext": ".eml"},
    "application/vnd.enliven": {"desc": "Enliven Viewer", "ext": ".nml"},
    "application/vnd.is-xpr": {"desc": "Express by Infoseek", "ext": ".xpr"},
    "image/vnd.xiff": {"desc": "eXtended Image File Format (XIFF)", "ext": ".xif"},
    "application/vnd.xfdl": {"desc": "Extensible Forms Description Language", "ext": ".xfdl"},
    "application/emma+xml": {"desc": "Extensible MultiModal Annotation", "ext": ".emma"},
    "application/vnd.ezpix-album": {"desc": "EZPix Secure Photo Album", "ext": ".ez2"},
    "application/vnd.ezpix-package": {"desc": "EZPix Secure Photo Album", "ext": ".ez3"},
    "image/vnd.fst": {"desc": "FAST Search & Transfer ASA", "ext": ".fst"},
    "video/vnd.fvt": {"desc": "FAST Search & Transfer ASA", "ext": ".fvt"},
    "image/vnd.fastbidsheet": {"desc": "FastBid Sheet", "ext": ".fbs"},
    "application/vnd.denovo.fcselayout-link": {"desc": "FCS Express Layout Link", "ext": ".fe_launch"},
    "video/x-f4v": {"desc": "Flash Video", "ext": ".f4v"},
    "video/x-flv": {"desc": "Flash Video", "ext": ".flv"},
    "image/vnd.fpx": {"desc": "FlashPix", "ext": ".fpx"},
    "image/vnd.net-fpx": {"desc": "FlashPix", "ext": ".npx"},
    "text/vnd.fmi.flexstor": {"desc": "FLEXSTOR", "ext": ".flx"},
    "video/x-fli": {"desc": "FLI/FLC Animation Format", "ext": ".fli"},
    "application/vnd.fluxtime.clip": {"desc": "FluxTime Clip", "ext": ".ftc"},
    "application/vnd.fdf": {"desc": "Forms Data Format", "ext": ".fdf"},
    "text/x-fortran": {"desc": "Fortran Source File", "ext": ".f"},
    "application/vnd.mif": {"desc": "FrameMaker Interchange Format", "ext": ".mif"},
    "application/vnd.framemaker": {"desc": "FrameMaker Normal Format", "ext": ".fm"},
    "image/x-freehand": {"desc": "FreeHand MX", "ext": ".fh"},
    "application/vnd.fsc.weblaunch": {"desc": "Friendly Software Corporation", "ext": ".fsc"},
    "application/vnd.frogans.fnc": {"desc": "Frogans Player", "ext": ".fnc"},
    "application/vnd.frogans.ltf": {"desc": "Frogans Player", "ext": ".ltf"},
    "application/vnd.fujixerox.ddd": {"desc": "Fujitsu - Xerox 2D CAD Data", "ext": ".ddd"},
    "application/vnd.fujixerox.docuworks": {"desc": "Fujitsu - Xerox DocuWorks", "ext": ".xdw"},
    "application/vnd.fujixerox.docuworks.binder": {"desc": "Fujitsu - Xerox DocuWorks Binder", "ext": ".xbd"},
    "application/vnd.fujitsu.oasys": {"desc": "Fujitsu Oasys", "ext": ".oas"},
    "application/vnd.fujitsu.oasys2": {"desc": "Fujitsu Oasys", "ext": ".oa2"},
    "application/vnd.fujitsu.oasys3": {"desc": "Fujitsu Oasys", "ext": ".oa3"},
    "application/vnd.fujitsu.oasysgp": {"desc": "Fujitsu Oasys", "ext": ".fg5"},
    "application/vnd.fujitsu.oasysprs": {"desc": "Fujitsu Oasys", "ext": ".bh2"},
    "application/x-futuresplash": {"desc": "FutureSplash Animator", "ext": ".spl"},
    "application/vnd.fuzzysheet": {"desc": "FuzzySheet", "ext": ".fzs"},
    "image/g3fax": {"desc": "G3 Fax Image", "ext": ".g3"},
    "application/vnd.gmx": {"desc": "GameMaker ActiveX", "ext": ".gmx"},
    "model/vnd.gtw": {"desc": "Gen-Trix Studio", "ext": ".gtw"},
    "application/vnd.genomatix.tuxedo": {"desc": "Genomatix Tuxedo Framework", "ext": ".txd"},
    "application/vnd.geogebra.file": {"desc": "GeoGebra", "ext": ".ggb"},
    "application/vnd.geogebra.tool": {"desc": "GeoGebra", "ext": ".ggt"},
    "model/vnd.gdl": {"desc": "Geometric Description Language (GDL)", "ext": ".gdl"},
    "application/vnd.geometry-explorer": {"desc": "GeoMetry Explorer", "ext": ".gex"},
    "application/vnd.geonext": {"desc": "GEONExT and JSXGraph", "ext": ".gxt"},
    "application/vnd.geoplan": {"desc": "GeoplanW", "ext": ".g2w"},
    "application/vnd.geospace": {"desc": "GeospacW", "ext": ".g3w"},
    "application/x-font-ghostscript": {"desc": "Ghostscript Font", "ext": ".gsf"},
    "application/x-font-bdf": {"desc": "Glyph Bitmap Distribution Format", "ext": ".bdf"},
    "application/x-gtar": {"desc": "GNU Tar Files", "ext": ".gtar"},
    "application/x-texinfo": {"desc": "GNU Texinfo Document", "ext": ".texinfo"},
    "application/x-gnumeric": {"desc": "Gnumeric", "ext": ".gnumeric"},
    "application/vnd.google-earth.kml+xml": {"desc": "Google Earth - KML", "ext": ".kml"},
    "application/vnd.google-earth.kmz": {"desc": "Google Earth - Zipped KML", "ext": ".kmz"},
    "application/vnd.grafeq": {"desc": "GrafEq", "ext": ".gqf"},
    "image/gif": {"desc": "Graphics Interchange Format", "ext": ".gif"},
    "text/vnd.graphviz": {"desc": "Graphviz", "ext": ".gv"},
    "application/vnd.groove-account": {"desc": "Groove - Account", "ext": ".gac"},
    "application/vnd.groove-help": {"desc": "Groove - Help", "ext": ".ghf"},
    "application/vnd.groove-identity-message": {"desc": "Groove - Identity Message", "ext": ".gim"},
    "application/vnd.groove-injector": {"desc": "Groove - Injector", "ext": ".grv"},
    "application/vnd.groove-tool-message": {"desc": "Groove - Tool Message", "ext": ".gtm"},
    "application/vnd.groove-tool-template": {"desc": "Groove - Tool Template", "ext": ".tpl"},
    "application/vnd.groove-vcard": {"desc": "Groove - Vcard", "ext": ".vcg"},
    "video/h261": {"desc": "H.261", "ext": ".h261"},
    "video/h263": {"desc": "H.263", "ext": ".h263"},
    "video/h264": {"desc": "H.264", "ext": ".h264"},
    "application/vnd.hp-hpid": {"desc": "Hewlett Packard Instant Delivery", "ext": ".hpid"},
    "application/vnd.hp-hps": {"desc": "Hewlett-Packard's WebPrintSmart", "ext": ".hps"},
    "application/x-hdf": {"desc": "Hierarchical Data Format", "ext": ".hdf"},
    "audio/vnd.rip": {"desc": "Hit'n'Mix", "ext": ".rip"},
    "application/vnd.hbci": {"desc": "Homebanking Computer Interface (HBCI)", "ext": ".hbci"},
    "application/vnd.hp-jlyt": {"desc": "HP Indigo Digital Press - Job Layout Languate", "ext": ".jlt"},
    "application/vnd.hp-pcl": {"desc": "HP Printer Command Language", "ext": ".pcl"},
    "application/vnd.hp-hpgl": {"desc": "HP-GL/2 and HP RTL", "ext": ".hpgl"},
    "application/vnd.yamaha.hv-script": {"desc": "HV Script", "ext": ".hvs"},
    "application/vnd.yamaha.hv-dic": {"desc": "HV Voice Dictionary", "ext": ".hvd"},
    "application/vnd.yamaha.hv-voice": {"desc": "HV Voice Parameter", "ext": ".hvp"},
    "application/vnd.hydrostatix.sof-data": {"desc": "Hydrostatix Master Suite", "ext": ".sfd-hdstx"},
    "application/hyperstudio": {"desc": "Hyperstudio", "ext": ".stk"},
    "application/vnd.hal+xml": {"desc": "Hypertext Application Language", "ext": ".hal"},
    "text/html": {"desc": "HyperText Markup Language (HTML)", "ext": ".html"},
    "application/vnd.ibm.rights-management": {"desc": "IBM DB2 Rights Manager", "ext": ".irm"},
    "application/vnd.ibm.secure-container": {"desc": "IBM Electronic Media Management System - Secure Container", "ext": ".sc"},
    "text/calendar": {"desc": "iCalendar", "ext": ".ics"},
    "application/vnd.iccprofile": {"desc": "ICC profile", "ext": ".icc"},
    "image/x-icon": {"desc": "Icon Image", "ext": ".ico"},
    "application/vnd.igloader": {"desc": "igLoader", "ext": ".igl"},
    "image/ief": {"desc": "Image Exchange Format", "ext": ".ief"},
    "application/vnd.immervision-ivp": {"desc": "ImmerVision PURE Players", "ext": ".ivp"},
    "application/vnd.immervision-ivu": {"desc": "ImmerVision PURE Players", "ext": ".ivu"},
    "application/reginfo+xml": {"desc": "IMS Networks", "ext": ".rif"},
    "text/vnd.in3d.3dml": {"desc": "In3D - 3DML", "ext": ".3dml"},
    "text/vnd.in3d.spot": {"desc": "In3D - 3DML", "ext": ".spot"},
    "model/iges": {"desc": "Initial Graphics Exchange Specification (IGES)", "ext": ".igs"},
    "application/vnd.intergeo": {"desc": "Interactive Geometry Software", "ext": ".i2g"},
    "application/vnd.cinderella": {"desc": "Interactive Geometry Software Cinderella", "ext": ".cdy"},
    "application/vnd.intercon.formnet": {"desc": "Intercon FormNet", "ext": ".xpw"},
    "application/vnd.isac.fcs": {"desc": "International Society for Advancement of Cytometry", "ext": ".fcs"},
    "application/ipfix": {"desc": "Internet Protocol Flow Information Export", "ext": ".ipfix"},
    "application/pkix-cert": {"desc": "Internet Public Key Infrastructure - Certificate", "ext": ".cer"},
    "application/pkixcmp": {"desc": "Internet Public Key Infrastructure - Certificate Management Protocole", "ext": ".pki"},
    "application/pkix-crl": {"desc": "Internet Public Key Infrastructure - Certificate Revocation Lists", "ext": ".crl"},
    "application/pkix-pkipath": {"desc": "Internet Public Key Infrastructure - Certification Path", "ext": ".pkipath"},
    "application/vnd.insors.igm": {"desc": "IOCOM Visimeet", "ext": ".igm"},
    "application/vnd.ipunplugged.rcprofile": {"desc": "IP Unplugged Roaming Client", "ext": ".rcprofile"},
    "application/vnd.irepository.package+xml": {"desc": "iRepository / Lucidoc Editor", "ext": ".irp"},
    "text/vnd.sun.j2me.app-descriptor": {"desc": "J2ME App Descriptor", "ext": ".jad"},
    "application/java-archive": {"desc": "Java Archive", "ext": ".jar"},
    "application/java-vm": {"desc": "Java Bytecode File", "ext": ".class"},
    "application/x-java-jnlp-file": {"desc": "Java Network Launching Protocol", "ext": ".jnlp"},
    "application/java-serialized-object": {"desc": "Java Serialized Object", "ext": ".ser"},
    "text/x-java-source": {"desc": "java, Java Source File", "ext": ".java"},
    "application/javascript": {"desc": "JavaScript", "ext": ".js"},
    "application/json": {"desc": "JavaScript Object Notation (JSON)", "ext": ".json"},
    "application/vnd.joost.joda-archive": {"desc": "Joda Archive", "ext": ".joda"},
    "video/jpm": {"desc": "JPEG 2000 Compound Image File Format", "ext": ".jpm"},
    "image/jpeg": {"desc": "JPEG Image", "ext": ".jpeg"},
    "video/jpeg": {"desc": "JPGVideo", "ext": ".jpgv"},
    "application/vnd.kahootz": {"desc": "Kahootz", "ext": ".ktz"},
    "application/vnd.chipnuts.karaoke-mmd": {"desc": "Karaoke on Chipnuts Chipsets", "ext": ".mmd"},
    "application/vnd.kde.karbon": {"desc": "KDE KOffice Office Suite - Karbon", "ext": ".karbon"},
    "application/vnd.kde.kchart": {"desc": "KDE KOffice Office Suite - KChart", "ext": ".chrt"},
    "application/vnd.kde.kformula": {"desc": "KDE KOffice Office Suite - Kformula", "ext": ".kfo"},
    "application/vnd.kde.kivio": {"desc": "KDE KOffice Office Suite - Kivio", "ext": ".flw"},
    "application/vnd.kde.kontour": {"desc": "KDE KOffice Office Suite - Kontour", "ext": ".kon"},
    "application/vnd.kde.kpresenter": {"desc": "KDE KOffice Office Suite - Kpresenter", "ext": ".kpr"},
    "application/vnd.kde.kspread": {"desc": "KDE KOffice Office Suite - Kspread", "ext": ".ksp"},
    "application/vnd.kde.kword": {"desc": "KDE KOffice Office Suite - Kword", "ext": ".kwd"},
    "application/vnd.kenameaapp": {"desc": "Kenamea App", "ext": ".htke"},
    "application/vnd.kidspiration": {"desc": "Kidspiration", "ext": ".kia"},
    "application/vnd.kinar": {"desc": "Kinar Applications", "ext": ".kne"},
    "application/vnd.kodak-descriptor": {"desc": "Kodak Storyshare", "ext": ".sse"},
    "application/vnd.las.las+xml": {"desc": "Laser App Enterprise", "ext": ".lasxml"},
    "application/x-latex": {"desc": "LaTeX", "ext": ".latex"},
    "application/vnd.llamagraphics.life-balance.desktop": {"desc": "Life Balance - Desktop Edition", "ext": ".lbd"},
    "application/vnd.llamagraphics.life-balance.exchange+xml": {"desc": "Life Balance - Exchange Format", "ext": ".lbe"},
    "application/vnd.jam": {"desc": "Lightspeed Audio Lab", "ext": ".jam"},
    "application/vnd.lotus-1-2-3": {"desc": "Lotus 1-2-3", "ext": ".123"},
    "application/vnd.lotus-approach": {"desc": "Lotus Approach", "ext": ".apr"},
    "application/vnd.lotus-freelance": {"desc": "Lotus Freelance", "ext": ".pre"},
    "application/vnd.lotus-notes": {"desc": "Lotus Notes", "ext": ".nsf"},
    "application/vnd.lotus-organizer": {"desc": "Lotus Organizer", "ext": ".org"},
    "application/vnd.lotus-screencam": {"desc": "Lotus Screencam", "ext": ".scm"},
    "application/vnd.lotus-wordpro": {"desc": "Lotus Wordpro", "ext": ".lwp"},
    "audio/vnd.lucent.voice": {"desc": "Lucent Voice", "ext": ".lvp"},
    "audio/x-mpegurl": {"desc": "M3U (Multimedia Playlist)", "ext": ".m3u"},
    "video/x-m4v": {"desc": "M4v", "ext": ".m4v"},
    "application/mac-binhex40": {"desc": "Macintosh BinHex 4.0", "ext": ".hqx"},
    "application/vnd.macports.portpkg": {"desc": "MacPorts Port System", "ext": ".portpkg"},
    "application/vnd.osgeo.mapguide.package": {"desc": "MapGuide DBXML", "ext": ".mgp"},
    "application/marc": {"desc": "MARC Formats", "ext": ".mrc"},
    "application/marcxml+xml": {"desc": "MARC21 XML Schema", "ext": ".mrcx"},
    "application/mxf": {"desc": "Material Exchange Format", "ext": ".mxf"},
    "application/vnd.wolfram.player": {"desc": "Mathematica Notebook Player", "ext": ".nbp"},
    "application/mathematica": {"desc": "Mathematica Notebooks", "ext": ".ma"},
    "application/mathml+xml": {"desc": "Mathematical Markup Language", "ext": ".mathml"},
    "application/mbox": {"desc": "Mbox database files", "ext": ".mbox"},
    "application/vnd.medcalcdata": {"desc": "MedCalc", "ext": ".mc1"},
    "application/mediaservercontrol+xml": {"desc": "Media Server Control Markup Language", "ext": ".mscml"},
    "application/vnd.mediastation.cdkey": {"desc": "MediaRemote", "ext": ".cdkey"},
    "application/vnd.mfer": {"desc": "Medical Waveform Encoding Format", "ext": ".mwf"},
    "application/vnd.mfmp": {"desc": "Melody Format for Mobile Platform", "ext": ".mfm"},
    "model/mesh": {"desc": "Mesh Data Type", "ext": ".msh"},
    "application/mads+xml": {"desc": "Metadata Authority Description Schema", "ext": ".mads"},
    "application/mets+xml": {"desc": "Metadata Encoding and Transmission Standard", "ext": ".mets"},
    "application/mods+xml": {"desc": "Metadata Object Description Schema", "ext": ".mods"},
    "application/metalink4+xml": {"desc": "Metalink", "ext": ".meta4"},
    "application/vnd.ms-powerpoint.template.macroenabled.12": {"desc": "Micosoft PowerPoint - Macro-Enabled Template File", "ext": ".potm"},
    "application/vnd.ms-word.document.macroenabled.12": {"desc": "Micosoft Word - Macro-Enabled Document", "ext": ".docm"},
    "application/vnd.ms-word.template.macroenabled.12": {"desc": "Micosoft Word - Macro-Enabled Template", "ext": ".dotm"},
    "application/vnd.mcd": {"desc": "Micro CADAM Helix D&D", "ext": ".mcd"},
    "application/vnd.micrografx.flo": {"desc": "Micrografx", "ext": ".flo"},
    "application/vnd.micrografx.igx": {"desc": "Micrografx iGrafx Professional", "ext": ".igx"},
    "application/vnd.eszigno3+xml": {"desc": "MICROSEC e-Szign垄", "ext": ".es3"},
    "application/x-msaccess": {"desc": "Microsoft Access", "ext": ".mdb"},
    "video/x-ms-asf": {"desc": "Microsoft Advanced Systems Format (ASF)", "ext": ".asf"},
    "application/x-msdownload": {"desc": "Microsoft Application", "ext": ".exe"},
    "application/vnd.ms-artgalry": {"desc": "Microsoft Artgalry", "ext": ".cil"},
    "application/vnd.ms-cab-compressed": {"desc": "Microsoft Cabinet File", "ext": ".cab"},
    "application/vnd.ms-ims": {"desc": "Microsoft Class Server", "ext": ".ims"},
    "application/x-ms-application": {"desc": "Microsoft ClickOnce", "ext": ".application"},
    "application/x-msclip": {"desc": "Microsoft Clipboard Clip", "ext": ".clp"},
    "image/vnd.ms-modi": {"desc": "Microsoft Document Imaging Format", "ext": ".mdi"},
    "application/vnd.ms-fontobject": {"desc": "Microsoft Embedded OpenType", "ext": ".eot"},
    "application/vnd.ms-excel": {"desc": "Microsoft Excel", "ext": ".xls"},
    "application/vnd.ms-excel.addin.macroenabled.12": {"desc": "Microsoft Excel - Add-In File", "ext": ".xlam"},
    "application/vnd.ms-excel.sheet.binary.macroenabled.12": {"desc": "Microsoft Excel - Binary Workbook", "ext": ".xlsb"},
    "application/vnd.ms-excel.template.macroenabled.12": {"desc": "Microsoft Excel - Macro-Enabled Template File", "ext": ".xltm"},
    "application/vnd.ms-excel.sheet.macroenabled.12": {"desc": "Microsoft Excel - Macro-Enabled Workbook", "ext": ".xlsm"},
    "application/vnd.ms-htmlhelp": {"desc": "Microsoft Html Help File", "ext": ".chm"},
    "application/x-mscardfile": {"desc": "Microsoft Information Card", "ext": ".crd"},
    "application/vnd.ms-lrm": {"desc": "Microsoft Learning Resource Module", "ext": ".lrm"},
    "application/x-msmediaview": {"desc": "Microsoft MediaView", "ext": ".mvb"},
    "application/x-msmoney": {"desc": "Microsoft Money", "ext": ".mny"},
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": {"desc": "Microsoft Office - OOXML - Presentation", "ext": ".pptx"},
    "application/vnd.openxmlformats-officedocument.presentationml.slide": {"desc": "Microsoft Office - OOXML - Presentation (Slide)", "ext": ".sldx"},
    "application/vnd.openxmlformats-officedocument.presentationml.slideshow": {"desc": "Microsoft Office - OOXML - Presentation (Slideshow)", "ext": ".ppsx"},
    "application/vnd.openxmlformats-officedocument.presentationml.template": {"desc": "Microsoft Office - OOXML - Presentation Template", "ext": ".potx"},
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": {"desc": "Microsoft Office - OOXML - Spreadsheet", "ext": ".xlsx"},
    "application/vnd.openxmlformats-officedocument.spreadsheetml.template": {"desc": "Microsoft Office - OOXML - Spreadsheet Template", "ext": ".xltx"},
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": {"desc": "Microsoft Office - OOXML - Word Document", "ext": ".docx"},
    "application/vnd.openxmlformats-officedocument.wordprocessingml.template": {"desc": "Microsoft Office - OOXML - Word Document Template", "ext": ".dotx"},
    "application/x-msbinder": {"desc": "Microsoft Office Binder", "ext": ".obd"},
    "application/vnd.ms-officetheme": {"desc": "Microsoft Office System Release Theme", "ext": ".thmx"},
    "application/onenote": {"desc": "Microsoft OneNote", "ext": ".onetoc"},
    "audio/vnd.ms-playready.media.pya": {"desc": "Microsoft PlayReady Ecosystem", "ext": ".pya"},
    "video/vnd.ms-playready.media.pyv": {"desc": "Microsoft PlayReady Ecosystem Video", "ext": ".pyv"},
    "application/vnd.ms-powerpoint": {"desc": "Microsoft PowerPoint", "ext": ".ppt"},
    "application/vnd.ms-powerpoint.addin.macroenabled.12": {"desc": "Microsoft PowerPoint - Add-in file", "ext": ".ppam"},
    "application/vnd.ms-powerpoint.slide.macroenabled.12": {"desc": "Microsoft PowerPoint - Macro-Enabled Open XML Slide", "ext": ".sldm"},
    "application/vnd.ms-powerpoint.presentation.macroenabled.12": {"desc": "Microsoft PowerPoint - Macro-Enabled Presentation File", "ext": ".pptm"},
    "application/vnd.ms-powerpoint.slideshow.macroenabled.12": {"desc": "Microsoft PowerPoint - Macro-Enabled Slide Show File", "ext": ".ppsm"},
    "application/vnd.ms-project": {"desc": "Microsoft Project", "ext": ".mpp"},
    "application/x-mspublisher": {"desc": "Microsoft Publisher", "ext": ".pub"},
    "application/x-msschedule": {"desc": "Microsoft Schedule+", "ext": ".scd"},
    "application/x-silverlight-app": {"desc": "Microsoft Silverlight", "ext": ".xap"},
    "application/vnd.ms-pki.stl": {"desc": "Microsoft Trust UI Provider - Certificate Trust Link", "ext": ".stl"},
    "application/vnd.ms-pki.seccat": {"desc": "Microsoft Trust UI Provider - Security Catalog", "ext": ".cat"},
    "application/vnd.visio": {"desc": "Microsoft Visio", "ext": ".vsd"},
    "video/x-ms-wm": {"desc": "Microsoft Windows Media", "ext": ".wm"},
    "audio/x-ms-wma": {"desc": "Microsoft Windows Media Audio", "ext": ".wma"},
    "audio/x-ms-wax": {"desc": "Microsoft Windows Media Audio Redirector", "ext": ".wax"},
    "video/x-ms-wmx": {"desc": "Microsoft Windows Media Audio/Video Playlist", "ext": ".wmx"},
    "application/x-ms-wmd": {"desc": "Microsoft Windows Media Player Download Package", "ext": ".wmd"},
    "application/vnd.ms-wpl": {"desc": "Microsoft Windows Media Player Playlist", "ext": ".wpl"},
    "application/x-ms-wmz": {"desc": "Microsoft Windows Media Player Skin Package", "ext": ".wmz"},
    "video/x-ms-wmv": {"desc": "Microsoft Windows Media Video", "ext": ".wmv"},
    "video/x-ms-wvx": {"desc": "Microsoft Windows Media Video Playlist", "ext": ".wvx"},
    "application/x-msmetafile": {"desc": "Microsoft Windows Metafile", "ext": ".wmf"},
    "application/x-msterminal": {"desc": "Microsoft Windows Terminal Services", "ext": ".trm"},
    "application/msword": {"desc": "Microsoft Word", "ext": ".doc"},
    "application/x-mswrite": {"desc": "Microsoft Wordpad", "ext": ".wri"},
    "application/vnd.ms-works": {"desc": "Microsoft Works", "ext": ".wps"},
    "application/x-ms-xbap": {"desc": "Microsoft XAML Browser Application", "ext": ".xbap"},
    "application/vnd.ms-xpsdocument": {"desc": "Microsoft XML Paper Specification", "ext": ".xps"},
    "audio/midi": {"desc": "MIDI - Musical Instrument Digital Interface", "ext": ".mid"},
    "application/vnd.ibm.minipay": {"desc": "MiniPay", "ext": ".mpy"},
    "application/vnd.ibm.modcap": {"desc": "MO:DCA-P", "ext": ".afp"},
    "application/vnd.jcp.javame.midlet-rms": {"desc": "Mobile Information Device Profile", "ext": ".rms"},
    "application/vnd.tmobile-livetv": {"desc": "MobileTV", "ext": ".tmo"},
    "application/x-mobipocket-ebook": {"desc": "Mobipocket", "ext": ".prc"},
    "application/vnd.mobius.mbk": {"desc": "Mobius Management Systems - Basket file", "ext": ".mbk"},
    "application/vnd.mobius.dis": {"desc": "Mobius Management Systems - Distribution Database", "ext": ".dis"},
    "application/vnd.mobius.plc": {"desc": "Mobius Management Systems - Policy Definition Language File", "ext": ".plc"},
    "application/vnd.mobius.mqy": {"desc": "Mobius Management Systems - Query File", "ext": ".mqy"},
    "application/vnd.mobius.msl": {"desc": "Mobius Management Systems - Script Language", "ext": ".msl"},
    "application/vnd.mobius.txf": {"desc": "Mobius Management Systems - Topic Index File", "ext": ".txf"},
    "application/vnd.mobius.daf": {"desc": "Mobius Management Systems - UniversalArchive", "ext": ".daf"},
    "text/vnd.fly": {"desc": "mod_fly / fly.cgi", "ext": ".fly"},
    "application/vnd.mophun.certificate": {"desc": "Mophun Certificate", "ext": ".mpc"},
    "application/vnd.mophun.application": {"desc": "Mophun VM", "ext": ".mpn"},
    "video/mj2": {"desc": "Motion JPEG 2000", "ext": ".mj2"},
    "audio/mpeg": {"desc": "MPEG Audio", "ext": ".mpga"},
    "video/vnd.mpegurl": {"desc": "MPEG Url", "ext": ".mxu"},
    "video/mpeg": {"desc": "MPEG Video", "ext": ".mpeg"},
    "application/mp21": {"desc": "MPEG-21", "ext": ".m21"},
    "audio/mp4": {"desc": "MPEG-4 Audio", "ext": ".mp4a"},
    "video/mp4": {"desc": "MPEG-4 Video", "ext": ".mp4"},
    "application/mp4": {"desc": "MPEG4", "ext": ".mp4"},
    "application/vnd.apple.mpegurl": {"desc": "Multimedia Playlist Unicode", "ext": ".m3u8"},
    "application/vnd.musician": {"desc": "MUsical Score Interpreted Code Invented for the ASCII designation of Notation", "ext": ".mus"},
    "application/vnd.muvee.style": {"desc": "Muvee Automatic Video Editing", "ext": ".msty"},
    "application/xv+xml": {"desc": "MXML", "ext": ".mxml"},
    "application/vnd.nokia.n-gage.data": {"desc": "N-Gage Game Data", "ext": ".ngdat"},
    "application/vnd.nokia.n-gage.symbian.install": {"desc": "N-Gage Game Installer", "ext": ".n-gage"},
    "application/x-dtbncx+xml": {"desc": "Navigation Control file for XML (for ePub)", "ext": ".ncx"},
    "application/x-netcdf": {"desc": "Network Common Data Form (NetCDF)", "ext": ".nc"},
    "application/vnd.neurolanguage.nlu": {"desc": "neuroLanguage", "ext": ".nlu"},
    "application/vnd.dna": {"desc": "New Moon Liftoff/DNA", "ext": ".dna"},
    "application/vnd.noblenet-directory": {"desc": "NobleNet Directory", "ext": ".nnd"},
    "application/vnd.noblenet-sealer": {"desc": "NobleNet Sealer", "ext": ".nns"},
    "application/vnd.noblenet-web": {"desc": "NobleNet Web", "ext": ".nnw"},
    "application/vnd.nokia.radio-preset": {"desc": "Nokia Radio Application - Preset", "ext": ".rpst"},
    "application/vnd.nokia.radio-presets": {"desc": "Nokia Radio Application - Preset", "ext": ".rpss"},
    "text/n3": {"desc": "Notation3", "ext": ".n3"},
    "application/vnd.novadigm.edm": {"desc": "Novadigm's RADIA and EDM products", "ext": ".edm"},
    "application/vnd.novadigm.edx": {"desc": "Novadigm's RADIA and EDM products", "ext": ".edx"},
    "application/vnd.novadigm.ext": {"desc": "Novadigm's RADIA and EDM products", "ext": ".ext"},
    "application/vnd.flographit": {"desc": "NpGraphIt", "ext": ".gph"},
    "audio/vnd.nuera.ecelp4800": {"desc": "Nuera ECELP 4800", "ext": ".ecelp4800"},
    "audio/vnd.nuera.ecelp7470": {"desc": "Nuera ECELP 7470", "ext": ".ecelp7470"},
    "audio/vnd.nuera.ecelp9600": {"desc": "Nuera ECELP 9600", "ext": ".ecelp9600"},
    "application/oda": {"desc": "Office Document Architecture", "ext": ".oda"},
    "application/ogg": {"desc": "Ogg", "ext": ".ogx"},
    "audio/ogg": {"desc": "Ogg Audio", "ext": ".oga"},
    "video/ogg": {"desc": "Ogg Video", "ext": ".ogv"},
    "application/vnd.oma.dd2+xml": {"desc": "OMA Download Agents", "ext": ".dd2"},
    "application/vnd.oasis.opendocument.text-web": {"desc": "Open Document Text Web", "ext": ".oth"},
    "application/oebps-package+xml": {"desc": "Open eBook Publication Structure", "ext": ".opf"},
    "application/vnd.intu.qbo": {"desc": "Open Financial Exchange", "ext": ".qbo"},
    "application/vnd.openofficeorg.extension": {"desc": "Open Office Extension", "ext": ".oxt"},
    "application/vnd.yamaha.openscoreformat": {"desc": "Open Score Format", "ext": ".osf"},
    "audio/webm": {"desc": "Open Web Media Project - Audio", "ext": ".weba"},
    "video/webm": {"desc": "Open Web Media Project - Video", "ext": ".webm"},
    "application/vnd.oasis.opendocument.chart": {"desc": "OpenDocument Chart", "ext": ".odc"},
    "application/vnd.oasis.opendocument.chart-template": {"desc": "OpenDocument Chart Template", "ext": ".otc"},
    "application/vnd.oasis.opendocument.database": {"desc": "OpenDocument Database", "ext": ".odb"},
    "application/vnd.oasis.opendocument.formula": {"desc": "OpenDocument Formula", "ext": ".odf"},
    "application/vnd.oasis.opendocument.formula-template": {"desc": "OpenDocument Formula Template", "ext": ".odft"},
    "application/vnd.oasis.opendocument.graphics": {"desc": "OpenDocument Graphics", "ext": ".odg"},
    "application/vnd.oasis.opendocument.graphics-template": {"desc": "OpenDocument Graphics Template", "ext": ".otg"},
    "application/vnd.oasis.opendocument.image": {"desc": "OpenDocument Image", "ext": ".odi"},
    "application/vnd.oasis.opendocument.image-template": {"desc": "OpenDocument Image Template", "ext": ".oti"},
    "application/vnd.oasis.opendocument.presentation": {"desc": "OpenDocument Presentation", "ext": ".odp"},
    "application/vnd.oasis.opendocument.presentation-template": {"desc": "OpenDocument Presentation Template", "ext": ".otp"},
    "application/vnd.oasis.opendocument.spreadsheet": {"desc": "OpenDocument Spreadsheet", "ext": ".ods"},
    "application/vnd.oasis.opendocument.spreadsheet-template": {"desc": "OpenDocument Spreadsheet Template", "ext": ".ots"},
    "application/vnd.oasis.opendocument.text": {"desc": "OpenDocument Text", "ext": ".odt"},
    "application/vnd.oasis.opendocument.text-master": {"desc": "OpenDocument Text Master", "ext": ".odm"},
    "application/vnd.oasis.opendocument.text-template": {"desc": "OpenDocument Text Template", "ext": ".ott"},
    "image/ktx": {"desc": "OpenGL Textures (KTX)", "ext": ".ktx"},
    "application/vnd.sun.xml.calc": {"desc": "OpenOffice - Calc (Spreadsheet)", "ext": ".sxc"},
    "application/vnd.sun.xml.calc.template": {"desc": "OpenOffice - Calc Template (Spreadsheet)", "ext": ".stc"},
    "application/vnd.sun.xml.draw": {"desc": "OpenOffice - Draw (Graphics)", "ext": ".sxd"},
    "application/vnd.sun.xml.draw.template": {"desc": "OpenOffice - Draw Template (Graphics)", "ext": ".std"},
    "application/vnd.sun.xml.impress": {"desc": "OpenOffice - Impress (Presentation)", "ext": ".sxi"},
    "application/vnd.sun.xml.impress.template": {"desc": "OpenOffice - Impress Template (Presentation)", "ext": ".sti"},
    "application/vnd.sun.xml.math": {"desc": "OpenOffice - Math (Formula)", "ext": ".sxm"},
    "application/vnd.sun.xml.writer": {"desc": "OpenOffice - Writer (Text - HTML)", "ext": ".sxw"},
    "application/vnd.sun.xml.writer.global": {"desc": "OpenOffice - Writer (Text - HTML)", "ext": ".sxg"},
    "application/vnd.sun.xml.writer.template": {"desc": "OpenOffice - Writer Template (Text - HTML)", "ext": ".stw"},
    "application/x-font-otf": {"desc": "OpenType Font File", "ext": ".otf"},
    "application/vnd.yamaha.openscoreformat.osfpvg+xml": {"desc": "OSFPVG", "ext": ".osfpvg"},
    "application/vnd.osgi.dp": {"desc": "OSGi Deployment Package", "ext": ".dp"},
    "application/vnd.palm": {"desc": "PalmOS Data", "ext": ".pdb"},
    "text/x-pascal": {"desc": "Pascal Source File", "ext": ".p"},
    "application/vnd.pawaafile": {"desc": "PawaaFILE", "ext": ".paw"},
    "application/vnd.hp-pclxl": {"desc": "PCL 6 Enhanced (Formely PCL XL)", "ext": ".pclxl"},
    "application/vnd.picsel": {"desc": "Pcsel eFIF File", "ext": ".efif"},
    "image/x-pcx": {"desc": "PCX Image", "ext": ".pcx"},
    "image/vnd.adobe.photoshop": {"desc": "Photoshop Document", "ext": ".psd"},
    "application/pics-rules": {"desc": "PICSRules", "ext": ".prf"},
    "image/x-pict": {"desc": "PICT Image", "ext": ".pic"},
    "application/x-chat": {"desc": "pIRCh", "ext": ".chat"},
    "application/pkcs10": {"desc": "PKCS #10 - Certification Request Standard", "ext": ".p10"},
    "application/x-pkcs12": {"desc": "PKCS #12 - Personal Information Exchange Syntax Standard", "ext": ".p12"},
    "application/pkcs7-mime": {"desc": "PKCS #7 - Cryptographic Message Syntax Standard", "ext": ".p7m"},
    "application/pkcs7-signature": {"desc": "PKCS #7 - Cryptographic Message Syntax Standard", "ext": ".p7s"},
    "application/x-pkcs7-certreqresp": {"desc": "PKCS #7 - Cryptographic Message Syntax Standard (Certificate Request Response)", "ext": ".p7r"},
    "application/x-pkcs7-certificates": {"desc": "PKCS #7 - Cryptographic Message Syntax Standard (Certificates)", "ext": ".p7b"},
    "application/pkcs8": {"desc": "PKCS #8 - Private-Key Information Syntax Standard", "ext": ".p8"},
    "application/vnd.pocketlearn": {"desc": "PocketLearn Viewers", "ext": ".plf"},
    "image/x-portable-anymap": {"desc": "Portable Anymap Image", "ext": ".pnm"},
    "image/x-portable-bitmap": {"desc": "Portable Bitmap Format", "ext": ".pbm"},
    "application/x-font-pcf": {"desc": "Portable Compiled Format", "ext": ".pcf"},
    "application/font-tdpfr": {"desc": "Portable Font Resource", "ext": ".pfr"},
    "application/x-chess-pgn": {"desc": "Portable Game Notation (Chess Games)", "ext": ".pgn"},
    "image/x-portable-graymap": {"desc": "Portable Graymap Format", "ext": ".pgm"},
    "image/png": {"desc": "Portable Network Graphics (PNG)", "ext": ".png"},
    "image/x-portable-pixmap": {"desc": "Portable Pixmap Format", "ext": ".ppm"},
    "application/pskc+xml": {"desc": "Portable Symmetric Key Container", "ext": ".pskcxml"},
    "application/vnd.ctc-posml": {"desc": "PosML", "ext": ".pml"},
    "application/postscript": {"desc": "PostScript", "ext": ".ai"},
    "application/x-font-type1": {"desc": "PostScript Fonts", "ext": ".pfa"},
    "application/vnd.powerbuilder6": {"desc": "PowerBuilder", "ext": ".pbd"},
    "application/pgp-encrypted": {"desc": "Pretty Good Privacy", "ext": ""},
    "application/pgp-signature": {"desc": "Pretty Good Privacy - Signature", "ext": ".pgp"},
    "application/vnd.previewsystems.box": {"desc": "Preview Systems ZipLock/VBox", "ext": ".box"},
    "application/vnd.pvi.ptid1": {"desc": "Princeton Video Image", "ext": ".ptid"},
    "application/pls+xml": {"desc": "Pronunciation Lexicon Specification", "ext": ".pls"},
    "application/vnd.pg.format": {"desc": "Proprietary P&G Standard Reporting System", "ext": ".str"},
    "application/vnd.pg.osasli": {"desc": "Proprietary P&G Standard Reporting System", "ext": ".ei6"},
    "text/prs.lines.tag": {"desc": "PRS Lines Tag", "ext": ".dsc"},
    "application/x-font-linux-psf": {"desc": "PSF Fonts", "ext": ".psf"},
    "application/vnd.publishare-delta-tree": {"desc": "PubliShare Objects", "ext": ".qps"},
    "application/vnd.pmi.widget": {"desc": "Qualcomm's Plaza Mobile Internet", "ext": ".wg"},
    "application/vnd.quark.quarkxpress": {"desc": "QuarkXpress", "ext": ".qxd"},
    "application/vnd.epson.esf": {"desc": "QUASS Stream Player", "ext": ".esf"},
    "application/vnd.epson.msf": {"desc": "QUASS Stream Player", "ext": ".msf"},
    "application/vnd.epson.ssf": {"desc": "QUASS Stream Player", "ext": ".ssf"},
    "application/vnd.epson.quickanime": {"desc": "QuickAnime Player", "ext": ".qam"},
    "application/vnd.intu.qfx": {"desc": "Quicken", "ext": ".qfx"},
    "video/quicktime": {"desc": "Quicktime Video", "ext": ".qt"},
    "application/x-rar-compressed": {"desc": "RAR Archive", "ext": ".rar"},
    "audio/x-pn-realaudio": {"desc": "Real Audio Sound", "ext": ".ram"},
    "audio/x-pn-realaudio-plugin": {"desc": "Real Audio Sound", "ext": ".rmp"},
    "application/rsd+xml": {"desc": "Really Simple Discovery", "ext": ".rsd"},
    "application/vnd.rn-realmedia": {"desc": "RealMedia", "ext": ".rm"},
    "application/vnd.realvnc.bed": {"desc": "RealVNC", "ext": ".bed"},
    "application/vnd.recordare.musicxml": {"desc": "Recordare Applications", "ext": ".mxl"},
    "application/vnd.recordare.musicxml+xml": {"desc": "Recordare Applications", "ext": ".musicxml"},
    "application/relax-ng-compact-syntax": {"desc": "Relax NG Compact Syntax", "ext": ".rnc"},
    "application/vnd.data-vision.rdz": {"desc": "RemoteDocs R-Viewer", "ext": ".rdz"},
    "application/rdf+xml": {"desc": "Resource Description Framework", "ext": ".rdf"},
    "application/vnd.cloanto.rp9": {"desc": "RetroPlatform Player", "ext": ".rp9"},
    "application/vnd.jisp": {"desc": "RhymBox", "ext": ".jisp"},
    "application/rtf": {"desc": "Rich Text Format", "ext": ".rtf"},
    "text/richtext": {"desc": "Rich Text Format (RTF)", "ext": ".rtx"},
    "application/vnd.route66.link66+xml": {"desc": "ROUTE 66 Location Based Services", "ext": ".link66"},
    "application/rss+xml": {"desc": "RSS - Really Simple Syndication", "ext":[".rss", ".xml"]},
    "application/shf+xml": {"desc": "S Hexdump Format", "ext": ".shf"},
    "application/vnd.sailingtracker.track": {"desc": "SailingTracker", "ext": ".st"},
    "image/svg+xml": {"desc": "Scalable Vector Graphics (SVG)", "ext": ".svg"},
    "application/vnd.sus-calendar": {"desc": "ScheduleUs", "ext": ".sus"},
    "application/sru+xml": {"desc": "Search/Retrieve via URL Response Format", "ext": ".sru"},
    "application/set-payment-initiation": {"desc": "Secure Electronic Transaction - Payment", "ext": ".setpay"},
    "application/set-registration-initiation": {"desc": "Secure Electronic Transaction - Registration", "ext": ".setreg"},
    "application/vnd.sema": {"desc": "Secured eMail", "ext": ".sema"},
    "application/vnd.semd": {"desc": "Secured eMail", "ext": ".semd"},
    "application/vnd.semf": {"desc": "Secured eMail", "ext": ".semf"},
    "application/vnd.seemail": {"desc": "SeeMail", "ext": ".see"},
    "application/x-font-snf": {"desc": "Server Normal Format", "ext": ".snf"},
    "application/scvp-vp-request": {"desc": "Server-Based Certificate Validation Protocol - Validation Policies - Request", "ext": ".spq"},
    "application/scvp-vp-response": {"desc": "Server-Based Certificate Validation Protocol - Validation Policies - Response", "ext": ".spp"},
    "application/scvp-cv-request": {"desc": "Server-Based Certificate Validation Protocol - Validation Request", "ext": ".scq"},
    "application/scvp-cv-response": {"desc": "Server-Based Certificate Validation Protocol - Validation Response", "ext": ".scs"},
    "application/sdp": {"desc": "Session Description Protocol", "ext": ".sdp"},
    "text/x-setext": {"desc": "Setext", "ext": ".etx"},
    "video/x-sgi-movie": {"desc": "SGI Movie", "ext": ".movie"},
    "application/vnd.shana.informed.formdata": {"desc": "Shana Informed Filler", "ext": ".ifm"},
    "application/vnd.shana.informed.formtemplate": {"desc": "Shana Informed Filler", "ext": ".itp"},
    "application/vnd.shana.informed.interchange": {"desc": "Shana Informed Filler", "ext": ".iif"},
    "application/vnd.shana.informed.package": {"desc": "Shana Informed Filler", "ext": ".ipk"},
    "application/thraud+xml": {"desc": "Sharing Transaction Fraud Data", "ext": ".tfi"},
    "application/x-shar": {"desc": "Shell Archive", "ext": ".shar"},
    "image/x-rgb": {"desc": "Silicon Graphics RGB Bitmap", "ext": ".rgb"},
    "application/vnd.epson.salt": {"desc": "SimpleAnimeLite Player", "ext": ".slt"},
    "application/vnd.accpac.simply.aso": {"desc": "Simply Accounting", "ext": ".aso"},
    "application/vnd.accpac.simply.imp": {"desc": "Simply Accounting - Data Import", "ext": ".imp"},
    "application/vnd.simtech-mindmapper": {"desc": "SimTech MindMapper", "ext": ".twd"},
    "application/vnd.commonspace": {"desc": "Sixth Floor Media - CommonSpace", "ext": ".csp"},
    "application/vnd.yamaha.smaf-audio": {"desc": "SMAF Audio", "ext": ".saf"},
    "application/vnd.smaf": {"desc": "SMAF File", "ext": ".mmf"},
    "application/vnd.yamaha.smaf-phrase": {"desc": "SMAF Phrase", "ext": ".spf"},
    "application/vnd.smart.teacher": {"desc": "SMART Technologies Apps", "ext": ".teacher"},
    "application/vnd.svd": {"desc": "SourceView Document", "ext": ".svd"},
    "application/sparql-query": {"desc": "SPARQL - Query", "ext": ".rq"},
    "application/sparql-results+xml": {"desc": "SPARQL - Results", "ext": ".srx"},
    "application/srgs": {"desc": "Speech Recognition Grammar Specification", "ext": ".gram"},
    "application/srgs+xml": {"desc": "Speech Recognition Grammar Specification - XML", "ext": ".grxml"},
    "application/ssml+xml": {"desc": "Speech Synthesis Markup Language", "ext": ".ssml"},
    "application/vnd.koan": {"desc": "SSEYO Koan Play File", "ext": ".skp"},
    "text/sgml": {"desc": "Standard Generalized Markup Language (SGML)", "ext": ".sgml"},
    "application/vnd.stardivision.calc": {"desc": "StarOffice - Calc", "ext": ".sdc"},
    "application/vnd.stardivision.draw": {"desc": "StarOffice - Draw", "ext": ".sda"},
    "application/vnd.stardivision.impress": {"desc": "StarOffice - Impress", "ext": ".sdd"},
    "application/vnd.stardivision.math": {"desc": "StarOffice - Math", "ext": ".smf"},
    "application/vnd.stardivision.writer": {"desc": "StarOffice - Writer", "ext": ".sdw"},
    "application/vnd.stardivision.writer-global": {"desc": "StarOffice - Writer (Global)", "ext": ".sgl"},
    "application/vnd.stepmania.stepchart": {"desc": "StepMania", "ext": ".sm"},
    "application/x-stuffit": {"desc": "Stuffit Archive", "ext": ".sit"},
    "application/x-stuffitx": {"desc": "Stuffit Archive", "ext": ".sitx"},
    "application/vnd.solent.sdkm+xml": {"desc": "SudokuMagic", "ext": ".sdkm"},
    "application/vnd.olpc-sugar": {"desc": "Sugar Linux Application Bundle", "ext": ".xo"},
    "audio/basic": {"desc": "Sun Audio - Au file format", "ext": ".au"},
    "application/vnd.wqd": {"desc": "SundaHus WQ", "ext": ".wqd"},
    "application/vnd.symbian.install": {"desc": "Symbian Install Package", "ext": ".sis"},
    "application/smil+xml": {"desc": "Synchronized Multimedia Integration Language", "ext": ".smi"},
    "application/vnd.syncml+xml": {"desc": "SyncML", "ext": ".xsm"},
    "application/vnd.syncml.dm+wbxml": {"desc": "SyncML - Device Management", "ext": ".bdm"},
    "application/vnd.syncml.dm+xml": {"desc": "SyncML - Device Management", "ext": ".xdm"},
    "application/x-sv4cpio": {"desc": "System V Release 4 CPIO Archive", "ext": ".sv4cpio"},
    "application/x-sv4crc": {"desc": "System V Release 4 CPIO Checksum Data", "ext": ".sv4crc"},
    "application/sbml+xml": {"desc": "Systems Biology Markup Language", "ext": ".sbml"},
    "text/tab-separated-values": {"desc": "Tab Separated Values", "ext": ".tsv"},
    "image/tiff": {"desc": "Tagged Image File Format", "ext": ".tiff"},
    "application/vnd.tao.intent-module-archive": {"desc": "Tao Intent", "ext": ".tao"},
    "application/x-tar": {"desc": "Tar File (Tape Archive)", "ext": ".tar"},
    "application/x-tcl": {"desc": "Tcl Script", "ext": ".tcl"},
    "application/x-tex": {"desc": "TeX", "ext": ".tex"},
    "application/x-tex-tfm": {"desc": "TeX Font Metric", "ext": ".tfm"},
    "application/tei+xml": {"desc": "Text Encoding and Interchange", "ext": ".tei"},
    "text/plain": {"desc": "Text File", "ext": ".txt"},
    "application/vnd.spotfire.dxp": {"desc": "TIBCO Spotfire", "ext": ".dxp"},
    "application/vnd.spotfire.sfs": {"desc": "TIBCO Spotfire", "ext": ".sfs"},
    "application/timestamped-data": {"desc": "Time Stamped Data Envelope", "ext": ".tsd"},
    "application/vnd.trid.tpt": {"desc": "TRI Systems Config", "ext": ".tpt"},
    "application/vnd.triscape.mxs": {"desc": "Triscape Map Explorer", "ext": ".mxs"},
    "text/troff": {"desc": "troff", "ext": ".t"},
    "application/vnd.trueapp": {"desc": "True BASIC", "ext": ".tra"},
    "application/x-font-ttf": {"desc": "TrueType Font", "ext": ".ttf"},
    "text/turtle": {"desc": "Turtle (Terse RDF Triple Language)", "ext": ".ttl"},
    "application/vnd.umajin": {"desc": "UMAJIN", "ext": ".umj"},
    "application/vnd.uoml+xml": {"desc": "Unique Object Markup Language", "ext": ".uoml"},
    "application/vnd.unity": {"desc": "Unity 3d", "ext": ".unityweb"},
    "application/vnd.ufdl": {"desc": "Universal Forms Description Language", "ext": ".ufd"},
    "text/uri-list": {"desc": "URI Resolution Services", "ext": ".uri"},
    "application/vnd.uiq.theme": {"desc": "User Interface Quartz - Theme (Symbian)", "ext": ".utz"},
    "application/x-ustar": {"desc": "Ustar (Uniform Standard Tape Archive)", "ext": ".ustar"},
    "text/x-uuencode": {"desc": "UUEncode", "ext": ".uu"},
    "text/x-vcalendar": {"desc": "vCalendar", "ext": ".vcs"},
    "text/x-vcard": {"desc": "vCard", "ext": ".vcf"},
    "application/x-cdlink": {"desc": "Video CD", "ext": ".vcd"},
    "application/vnd.vsf": {"desc": "Viewport+", "ext": ".vsf"},
    "model/vrml": {"desc": "Virtual Reality Modeling Language", "ext": ".wrl"},
    "application/vnd.vcx": {"desc": "VirtualCatalog", "ext": ".vcx"},
    "model/vnd.mts": {"desc": "Virtue MTS", "ext": ".mts"},
    "model/vnd.vtu": {"desc": "Virtue VTU", "ext": ".vtu"},
    "application/vnd.visionary": {"desc": "Visionary", "ext": ".vis"},
    "video/vnd.vivo": {"desc": "Vivo", "ext": ".viv"},
    "application/ccxml+xml": {"desc":"Voice Browser Call Control", "ext":".ccxml"},
    "application/voicexml+xml": {"desc": "VoiceXML", "ext": ".vxml"},
    "application/x-wais-source": {"desc": "WAIS Source", "ext": ".src"},
    "application/vnd.wap.wbxml": {"desc": "WAP Binary XML (WBXML)", "ext": ".wbxml"},
    "image/vnd.wap.wbmp": {"desc": "WAP Bitamp (WBMP)", "ext": ".wbmp"},
    "audio/x-wav": {"desc": "Waveform Audio File Format (WAV)", "ext": ".wav"},
    "application/davmount+xml": {"desc": "Web Distributed Authoring and Versioning", "ext": ".davmount"},
    "application/x-font-woff": {"desc": "Web Open Font Format", "ext": ".woff"},
    "application/wspolicy+xml": {"desc": "Web Services Policy", "ext": ".wspolicy"},
    "image/webp": {"desc": "WebP Image", "ext": ".webp"},
    "application/vnd.webturbo": {"desc": "WebTurbo", "ext": ".wtb"},
    "application/widget": {"desc": "Widget Packaging and XML Configuration", "ext": ".wgt"},
    "application/winhlp": {"desc": "WinHelp", "ext": ".hlp"},
    "text/vnd.wap.wml": {"desc": "Wireless Markup Language (WML)", "ext": ".wml"},
    "text/vnd.wap.wmlscript": {"desc": "Wireless Markup Language Script (WMLScript)", "ext": ".wmls"},
    "application/vnd.wap.wmlscriptc": {"desc": "WMLScript", "ext": ".wmlsc"},
    "application/vnd.wordperfect": {"desc": "Wordperfect", "ext": ".wpd"},
    "application/vnd.wt.stf": {"desc": "Worldtalk", "ext": ".stf"},
    "application/wsdl+xml": {"desc": "WSDL - Web Services Description Language", "ext": ".wsdl"},
    "image/x-xbitmap": {"desc": "X BitMap", "ext": ".xbm"},
    "image/x-xpixmap": {"desc": "X PixMap", "ext": ".xpm"},
    "image/x-xwindowdump": {"desc": "X Window Dump", "ext": ".xwd"},
    "application/x-x509-ca-cert": {"desc": "X.509 Certificate", "ext": ".der"},
    "application/x-xfig": {"desc": "Xfig", "ext": ".fig"},
    "application/xhtml+xml": {"desc": "XHTML - The Extensible HyperText Markup Language", "ext": ".xhtml"},
    "application/xml": {"desc": "XML - Extensible Markup Language", "ext": ".xml"},
    "application/xcap-diff+xml": {"desc": "XML Configuration Access Protocol - XCAP Diff", "ext": ".xdf"},
    "application/xenc+xml": {"desc": "XML Encryption Syntax and Processing", "ext": ".xenc"},
    "application/patch-ops-error+xml": {"desc": "XML Patch Framework", "ext": ".xer"},
    "application/resource-lists+xml": {"desc": "XML Resource Lists", "ext": ".rl"},
    "application/rls-services+xml": {"desc": "XML Resource Lists", "ext": ".rs"},
    "application/resource-lists-diff+xml": {"desc": "XML Resource Lists Diff", "ext": ".rld"},
    "application/xslt+xml": {"desc": "XML Transformations", "ext": ".xslt"},
    "application/xop+xml": {"desc": "XML-Binary Optimized Packaging", "ext": ".xop"},
    "application/x-xpinstall": {"desc": "XPInstall - Mozilla", "ext": ".xpi"},
    "application/xspf+xml": {"desc": "XSPF - XML Shareable Playlist Format", "ext": ".xspf"},
    "application/vnd.mozilla.xul+xml": {"desc": "XUL - XML User Interface Language", "ext": ".xul"},
    "chemical/x-xyz": {"desc": "XYZ File Format", "ext": ".xyz"},
    "application/yang": {"desc": "YANG Data Modeling Language", "ext": ".yang"},
    "application/yin+xml": {"desc": "YIN (YANG - XML)", "ext": ".yin"},
    "application/vnd.zul": {"desc": "Z.U.L. Geometry", "ext": ".zir"},
    "application/zip": {"desc": "Zip Archive", "ext": ".zip"},
    "application/vnd.handheld-entertainment+xml": {"desc": "ZVUE Media Manager", "ext": ".zmm"},
    "application/vnd.zzazz.deck+xml": {"desc": "Zzazz Deck", "ext": ".zaz"},
    "text/directory": {"desc": "目录", "ext": "folder"}
}

function typeTranslator(type , defaultReturn = 'undefined') {
        return type === undefined ? defaultReturn :
            typeDictory[type] === undefined ? defaultReturn :
                typeDictory[type]['desc'] ?? defaultReturn;
}

export default typeTranslator;
